### ISSUE TITLE
Automatically use hard tabs for Makefile buffers

### ISSUE THREAD

**Issue by cbednarski** [atom/language-make#3]
Since makefiles require hard tabs, I'd like Atom to automatically use hard tabs whenever I'm editing a Makefile. Atom already detects the buffer type automatically.

Sublime Text accomplishes this via language-specific configuration files. So for example, I can independently specify 2 spaces default for javascript, 4 spaces default for python, and hard tab default for Makefiles. Not sure if this makes sense in Atom land but it seems like a simple way to do it.

**Comment by rgbkrk** [comment]
Could my own settings be overriding this somehow? I'm still ending up with spaces by default.

**Comment by rgbkrk** [comment]
To answer my own question, it's a result of `soft` being set instead of `auto` in settings under "Tab Type":

<img width="780" alt="screenshot 2015-10-15 17 09 21" src="https://cloud.githubusercontent.com/assets/836375/10528964/846433b6-735f-11e5-82fc-6e918418c157.png">

**Comment by thomasjo** [comment]
@rgbkrk The language settings should win, and in the case of language-make, the [tab type is set `hard`](https://github.com/atom/language-make/blob/v0.19.0/settings/language-make.cson#L5).

@atom/feedback Can any of you repro this?

**Comment by 50Wliu** [comment]
I believe it's because Make 0.19.0 isn't installed on Atom 1.0.19.
https://github.com/atom/atom/blob/7229d1a4295dd0fcb644b7c891a64e6836b2c3b2/package.json#L138

**Comment by DJviolin** [comment]
@50Wliu I installed the language-make 0.19.0 with `apm install language-make` command, but still inserting spaces instead of tabs. :(

**Comment by asbjornu** [comment]
I'm still struggling like a nutbag with this in Atom 1.4.1. I've tried every possible setting of "Soft Tabs" and "Tab Type". I've tried to [convert spaces to tabs](https://github.com/lee-dohm/tabs-to-spaces). Whatever I do; when the `Makefile` is saved, it has spaces in it.

Checking "Show invisibles" reveals that I do get tabs when I press the tab key (represented by `»`) in the editor, but when I save, they are replaced with spaces. What the heck is causing this? Would you know, @thomasjo?

**Comment by thomasjo** [comment]
@asbjornu Are you able to reproduce the behavior in safe mode? `atom --safe`. Nothing in Atom (should) perform anything like this on save, so I'm guessing this is actually caused by the tabs-to-spaces package (which has "on save" behavior).

**Comment by asbjornu** [comment]
@thomasjo You're right. As I've updated my comment above, tabs-to-spaces and its `onSave` functionality is to blame. I was just dumbfounded that it was doing its thing even though I had disabled the package. Adjusting the configuration also doesn't help, so I'm creating an issue with it.

**Comment by sunjay** [comment]
For anyone who ends up here from Google and sees @asbjornu's configuration, it needs to look like this:

```yml
"*":
  "tabs-to-spaces":
    "onSave": "untabify"
".source.makefile":
  "tabs-to-spaces":
    "onSave": "tabify"
```

This was addressed in: https://github.com/lee-dohm/tabs-to-spaces/issues/42

**Comment by braadworst** [comment]
@sunjay, ace! I couldnt figure out what the scope key name was for makefiles.

**Comment by bennabiy** [comment]
I am still having this issue, but not sure what package is causing it as I do not have tabs-to-spaces installed. I have tabs in my Makefile, but on save, I get 8 spaces instead.

**Comment by bennabiy** [comment]
I may be dense, but where do I set those settings to make it work?

**Comment by dcburleigh** [comment]
How do I tell Atom which files are makefiles? I have some files like makefile.dev, makefile.inc,
and I'd like Atom to give me hard tabs, syntax highlighting, etc.

**Comment by 50Wliu** [comment]
@dcburleigh you can use the Grammar Selector (Ctrl+Shift+L on Windows/Linux, cmd-shift-L on macOS), or follow the instructions at https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539.

**Comment by richardPFisk** [comment]
I had some joy using `.editorconfig` with this setting: 
```
[Makefile]
indent_style = tab
```
